version: "3.8"

services:
  airflow:
    image: apache/airflow:latest
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    environment:
      - _AIRFLOW_WWW_USER_USERNAME=airflow
      - _AIRFLOW_WWW_USER_PASSWORD=password
      - AIRFLOW_CONN_OPENWEATHER_API=http://api.openweathermap.org/
      - AIRFLOW_CONN_MINIO_CONN=aws://admin:password@minio:9000/?endpoint_url=http%3A//minio%3A9000&region_name=us-east-1
    command: airflow standalone
    depends_on:
      - minio
    networks:
      - airflow-network

  # UNCOMMENTED MinIO service - this was your main problem!
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      # Use the same credentials as in your connection string
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - airflow-network

volumes:
  minio_data:

networks:
  airflow-network:
    driver: bridge
